---
title: "Datos de cantones de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes}
# Carga de paquetes

library(dplyr)
library(sf)
library(DT)
library(ggplot2)
library(plotly)
library(leaflet)
```

```{r lectura-datos}
# Lectura de datos

cantones <-
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```


Row {data-height=10}
-----------------------------------------------------------------------

### **Fuente de los datos: [Organismo de Investigación Judicial (OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)**

Row {data-height=590}
-----------------------------------------------------------------------

### Mapa

```{r}
# Mapa

leaflet() %>%
  setView(lng = -84.19452,
          lat = 9.572735,
          zoom = 7) %>%
  addTiles(group = "OpenStreetMap") %>%
  addPolygons(
    data = cantones,
    color = "black",
    opacity = 0.2,
    weight = 1.5,
    popup = paste(
      paste("<a>Cantón:</a>", cantones$canton),
      paste("<a>Área:</a>", cantones$area, "km2"),
      sep = "<br>"
    ),
    group = "Cantones"
  ) %>%
  addLayersControl(baseGroups = c("OpenStreetMap"),
                   overlayGroups = c("Cantones"))
```

### Tabla

```{r tabla}
# Tabla

cantones %>%
  st_drop_geometry() %>%
  select(provincia, canton, area) %>%
  arrange(desc(area)) %>%
  datatable(
    colnames = c("Provincia", "Cantón", "Área"),
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

Row {data-height=400}
-----------------------------------------------------------------------

### Gráfico de cantones con mayor área

```{r grafico}
# Gráfico

grafico_ggplot2 <-
  cantones %>%
  st_drop_geometry() %>%
  slice_max(area, n = 20) %>%
  ggplot(aes(x = reorder(canton, -area), y = area)) +
  geom_bar(stat = "identity") +
  xlab("Cantón") +
  ylab("Área (km2)")

ggplotly(grafico_ggplot2)
```

